const router = require('express').Router()
const {register,bookRoom, login, forgotPassword,resetPassword, validateMobile,otpSignIn,getHotels,getHotelImages,getSingleHotelData, countByCity, confirmBooking, verifyPayment, getBooking, retainHotelRoom, getUserWiseBooking, cancelBooking, updateBookedBy, payUsingWallet, searchCities} = require("../controllers/userController")

router.post("/register",register)
router.post("/login",login)
router.post("/forgot/password",forgotPassword)
router.post("/reset/password/:id/:token",resetPassword)
router.post("/validate/mobile",validateMobile)
router.post("/send/otp",otpSignIn)
router.get("/hotels",getHotels)
router.get("/get/images",getHotelImages)
router.get('/get/details/:id',getSingleHotelData)
router.get('/countByCity',countByCity)
router.post('/book/room',bookRoom)
router.post('/confirm/booking/:id',confirmBooking)
router.get('/get/booking/:id',getBooking)
router.post ('/payment/success',verifyPayment)
router.get('/room/count/:id',retainHotelRoom)
router.get('/user/booking/:id',getUserWiseBooking)
router.post('/cancel/booking/:id',cancelBooking)
router.put('/add/bookedby/:id',updateBookedBy)
router.put('/pay/using/wallet/:id',payUsingWallet)
router.get('/search/cities',searchCities)

module.exports = router;