const host = 'http://localhost:5000'

export const registerUrl = `${host}/register`;
export const loginUrl = `${host}/login`;
export const forgetUrl = `${host}/forgot/password`
export const passwordReset = `${host}/reset/password`
export const validateMobileURL = `${host}/validate/mobile`
export const sendOtpURL = `${host}/send/otp`
export const getHotels = `${host}/hotels`
export const getHotelImagesURL = `${host}/get/images`
export const getRoomCmpltURL = `${host}/get/details`
export const bookRoomUrl = `${host}/book/room` 
export const confirmBooking = `${host}/confirm/booking`
export const getBookingDetails = `${host}/get/booking`
export const verifyUrl = `${host}/payment/success`
export const retainRoomUrl = `${host}/room/count`
export const getUserWiseBookingUrl = `${host}/user/booking`
export const bookingCancelUrl = `${host}/cancel/booking`
export const updateBookedByUrl = `${host}/add/bookedby`
export const payUsingWalletUrl = `${host}/pay/using/wallet`
export const searchCities = `${host}/search/cities`